### PR TITLE
Renamed project to CC Search Portal, all graphics occurrences

### LINKED ISSUE #55: Rename project to CC Search Portal, all graphic occurrences
## Description
The logo image present here on the homepage:

Screen Shot 2022-10-06 at 3 27 58 PM

### PR DESCRIPTION
**Pull request by ImaJin14**
## Fixes

Fixes #55   by @possumbilities 

## Description

Renames project to CC Search Portal alongside all graphics occurrences

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source license" is equivalent to "open content license or public domain dedication."
<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by possumbilities** [comment]
@ImaJin14 also, let's hyphenate the .png file name as `cc-search-portal.png` if the name is going to change.

**Comment by ImaJin14** [comment]
@possumbilities changes made please review pr

**Comment by possumbilities** [comment]
@ImaJin14 There's still changes happening well beyond just the graphic file and its alt text that don't need to be a part of this PR.

**Comment by ImaJin14** [comment]
Okay @possumbilities I'll get to getting it fixed

**Comment by ImaJin14** [comment]
@possumbilities all changes have been made

**Comment by possumbilities** [comment]
@ImaJin14 It's still showing that files beyond the scope of this PR have been changed. the `README.md` and `search.js` files shouldn't need alteration.

 Additionally, I believe there are now merge conflicts you'll need to address as well.

**Comment by ImaJin14** [comment]
@possumbilities all changes have been made now please review

**Comment by possumbilities** [comment]
@ImaJin14 Unfortunately, it seems that in resolving the conflicts you have reverted all the changes you made in #56 . If you check the `Files changed` tab on this page you can see what I'm referring to.

To be more specific the only changes that this PR should show on that tab should be the `cc-search.png` file name changing to `cc-search-portal.png`, and being updated to reflect the new title, and the `index.php` file should have the relevant image alt text updated too. 

Any additional changes to other files aren't needed, and in this case undo previous work.

**Pull request closed without merging**
