### PR TITLE
Add nappy external resource 

### PR DESCRIPTION
**Pull request by dikehprosper**
## Fixes
Fixes https://github.com/creativecommons/search/issues/115 by @dikehprosper

## Description
Included [Nappy](https://nappy.co/) in the external sources section of the CC search portal along with the redirection functionality to Nappy search

## Technical details
- Added the Nappy element to the page (html) at the correct position following lexicographical order, in index.php
- Implemented the Nappy search redirection functionality in both the index.php and search.js files

## Screenshots

197743007-aee2102c-6f52-41f0-bdbc-85d861b3007c

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source license" is equivalent to "open content license or public domain dedication."
<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by dullbenz** [comment]
The external source list should follow lexicographical order as indicated by @TimidRobot in this issue #109

**Comment by dikehprosper** [comment]
@dullbenz working on it

**Comment by dikehprosper** [comment]
this is a new screenshot with the latest change(engines corrected to lexicographical order
Screenshot 2022-10-25 150032

**Comment by possumbilities** [comment]
@dikehprosper Looks like the PR is a little out of date with main

**Comment by dikehprosper** [comment]
@possumbilities its up-to-date now ma'am

**Comment by possumbilities** [comment]
@dikehprosper In following with the rest of the file conventions, when you're adding the term `nappy` in the codebase, it should be lowercase to match all the other engines use cases as well. In most cases you have it has `Nappy`, when all the other engines are using full lowercase instances.

**Comment by dikehprosper** [comment]
@possumbilities working on it now

**Review by possumbilities — APPROVED** [review]
Well done! Tested via Docker, works as expected! ❤️

**Comment by dikehprosper** [comment]
@possumbilities thanks ma'am

**Pull request merged**
