### PR TITLE
Implementation of new Footer component

### LINKED ISSUE #60: [Feature] Redesign Footer component
## Problem
The current footer is really bad visually and does not meet the current standards of other UI/UX trend 

## Description
This feature will make the Footer more pleasing to look at and more accessible

## Additional context
For me personally as a Frontend Developer the current Footer is way below standard with the ever evolving world of UI/UX
The overall goal for the new footer is to put it in alignment with the current universal footer found on newer Creative Commons sites. See an example here: https://opensource.creativecommons.org/

Screenshot (161)

## Implementation

- [x] I would be interested in implementing this feature.

### PR DESCRIPTION
**Pull request by OsujiPius**
## Fixes
Fixes #60  by @OsujiPius

## Description
The PR implements the brand new footer component similar to the one used in [creativecommons.org](url)

## Tests
Start up the project locally on localhost:8080

## Screenshots
Screenshot (172)

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source license" is equivalent to "open content license or public domain dedication."
<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by dikehprosper** [comment]
@OsujiPius looks good

**Comment by OsujiPius** [comment]
@dikehprosper thanks a bunch 😉

**Comment by possumbilities** [comment]
Thank you for taking the time to submit this PR as a contribution! ❤️ 

As noted, on the Issue related to this, the Footer should follow the footer from https://opensource.creativecommons.org/ (I think that may have been what you meant instead when you wrong creativecommons.org). 

You can see the difference by comparison that this PR does not match the footer precisely, which should look like this instead:
Screen Shot 2022-10-17 at 2 23 26 PM

The mismatches would need to be corrected to account for this, before this PR could be accepted and merged.

**Comment by OsujiPius** [comment]
> Please see above comment about the mismatch in styles.

@possumbilities working on the changes now

**Comment by Rubadel** [comment]
Good work , all the best

**Comment by mbonamensa** [comment]
@OsujiPius are you still working on this?

**Comment by possumbilities** [comment]
@OsujiPius Closing this as stale. If you work out a stable implementation at a future date, please feel free to submit a fresh PR ❤️

**Pull request closed without merging**
