### PR TITLE
remove styles from index.php and place them in style.css

### LINKED ISSUE #92: [Bug] <Remove styles in index.php and place them in style.css>
## Description

Styles have been placed within the page markup. This is not the best practice and can make the markup code look messy.

## Reproduction

1. Open cc search in your editor
2. Navigate to index.php
3. Check lines 235 and 261
4. See error.

## Expectation

It is best practice to keep styles separately from the markup. This will make the markup cleaner and the styles easy to maintain.

## Screenshots

This ```<p>``` already has a selector in style.css. See next screenshot
Screenshot (42)

The code from the markup can be added here.
Screenshot (44)

Another instance 
Screenshot (43)

## Resolution

- [x] I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by mbonamensa**
## Fixes

Fixes #92  by @mbonamensa 

## Description

This pull request removes the styles that are in the markup file, `index.php` to the stylesheet `style.css` making the markup cleaner and the stylesheet easily maintainable.

## Technical details

I changed the color from `color: white;` to `color: #ffffff;` as best practice.

## Tests

1. Open cc search in the editor
2. Navigate to index.php
3. Check lines 235 and 261
4. See styles removed
5. Go back to cc search root folder
6. Navigate to style.css
7. Check lines 19 and 158
8. See added styles

## Screenshots

Problem: style in markup
Screenshot (42)

Screenshot (43)

Solution: style moved to stylesheet
Screenshot (48)

Screenshot (47)

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source license" is equivalent to "open content license or public domain dedication."
<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by EnayiOnaji** [comment]
Hello, 
please how can i make my contribution to to project

**Comment by possumbilities** [comment]
@EnayiOnaji you could note any corrections or changes you think still need to be made on this PR that are not present in the current code commits.

**Comment by mbonamensa** [comment]
> Hello, please how can i make my contribution to to project

There are some good first issues that have been opened today. You can check them out here: https://github.com/creativecommons/search/issues

**Review by possumbilities — APPROVED** [review]
Tested via docker, and I believe there's no ill effects. Well done, and thank you! ❤️

**Comment by mbonamensa** [comment]
Thank you! @possumbilities 
This will be my very first Open Source contribution that has been approved. 
Thank you for giving me the opportunity ❤️

**Pull request merged**
