### PR TITLE
Add The Greats as a search engine

### LINKED ISSUE #145: [Feature] Add 'The Greats' as an external source
## Problem
The goal is to add a good number of external sources to give users a variety of results from different sources.

## Description
[The Greats](https://www.thegreats.co/thegreats/public/artworks) is a free site to discover awesome themed art illustrations. it is also licensed under [Creative Commons Attribution-NonCommercial 4.0 International](https://creativecommons.org/licenses/by-nc/4.0/)..Gotten from the additional sources list of Openverse available in the file [get-additional-sources.ts](https://github.com/WordPress/openverse-frontend/blob/main/src/utils/get-additional-sources.ts#L61) mentioned in https://github.com/creativecommons/search/issues/48

Adding The Greatss as an external source to CC search will be a good addition and will benefit our users by giving them more search options.

## Implementation

- [x] I would be interested in implementing this feature.

### PR DESCRIPTION
**Pull request by PreciousOritsedere**
## Fixes

Fixes #145 by @PreciousOritsedere 

## Description
This PR adds "The Greats" as an additional search engine
Screenshot (86)

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source license" is equivalent to "open content license or public domain dedication."
<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by PreciousOritsedere** [comment]
> @PreciousOritsedere please finish completing the checklist as relevant ❤️

I’m a bit confused. Could you please expatiate more on what you mean? Or possibly guide me in the right direction on what to do please

**Comment by PreciousOritsedere** [comment]
> @PreciousOritsedere please finish completing the checklist as relevant ❤️

I’ve done so now

**Comment by possumbilities** [comment]
@PreciousOritsedere PR is out of date with main

**Comment by PreciousOritsedere** [comment]
> @PreciousOritsedere PR is out of date with main

Can you guide me on how to fix this please

**Comment by possumbilities** [comment]
@PreciousOritsedere sure, I can try. Looking at how you are doing things, what you would likely need to do on your local setup is:

in your commandline while working in your local codebase,

`git fetch origin`

then,
`git merge origin/main`

then you can do a git push to your forked repo, and it should reflect here.

I should note for others, that it's usually a good idea to work in a branch that's not main and if that's what someone is doing the instructions above will need to differ.

**Comment by PreciousOritsedere** [comment]
> @PreciousOritsedere sure, I can try. Looking at how you are doing things, what you would likely need to do on your local setup is:
> 
> in your commandline while working in your local codebase,
> 
> `git fetch origin`
> 
> then, `git merge origin/main`
> 
> then you can do a git push to your forked repo, and it should reflect here.
> 
> I should note for others, that it's usually a good idea to work in a branch that's not main and if that's what someone is doing the instructions above will need to differ.

Okay I’ll try this. Thank you

**Comment by PreciousOritsedere** [comment]
@possumbilities i have carried out your instructions. I think it’s up to date now

**Comment by possumbilities** [comment]
@PreciousOritsedere Thank you for all your work here, but since the Greats currently conflicts with the limits of the current CC Search Portal UX there's no reliable way to merge this, but that's likely to be possible down the line when the UX improves. ❤️

**Comment by PreciousOritsedere** [comment]
> @PreciousOritsedere Thank you for all your work here, but since the Greats currently conflicts with the limits of the current CC Search Portal UX there's no reliable way to merge this, but that's likely to be possible down the line when the UX improves. ❤️

Okay. Thank you

**Pull request closed without merging**
