### PR TITLE
Clean up space and tab formatting in CSS files

### LINKED ISSUE #65: [Bug] Cleanup Codebase CSS files tab and spacing formatting
## Description
The codebase currently has a lot of duplicates of code and files that do not seem necessary. There is also a lot of generic errors especially in the CSS files which can cause a lot of confusion especially to people new to the codebase.

## Reproduction
1. Open `ie8-and-down.css`
2. Open `primary.styles.css`
3. Open `style.css`

## Expectation
1. Fix all errors in the CSS files 
2. Remove all unused code

##Additional Context
The errors in the CSS range from wrong `Syntax` and No opening curly brace in one instance

## Screenshots

Screenshot (162)
Screenshot (163)
Screenshot (164)

## Resolution

- [x] I would be interested in resolving this bug.

### LINKED ISSUE #76: [Bug] <Removing line inconsistency and correcting tab spacing in style.css>
## Description

I will like to remove line inconsistency and correct tab spacing in style.css

## Reproduction
1. open cc search in editor.
1. navigate to style.css file.
1. check lines 9, 15, 23...
1. see error.

## Expectation

The line spacing in 
> style.css file should be consistent so that the code will be more organized.
> tab spacing should be corrected as well.

## Screenshots

1st Report

## Resolution

- [x] I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by PreciousOritsedere**
## Fixes
Fixed all errors in the CSS files
Removed all unused code
Fixes #65  by @OsujiPius and fixes #76 by @AnnyTheExplorer

## Description
This PR cleans the code base by fixing all syntax errors, correcting line inconsistency and removing all unused codes, to make the code base clean and more readable. 

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source license" is equivalent to "open content license or public domain dedication."
<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by ImaJin14** [comment]
@PreciousOritsedere you've removed some commented out codes that i think where places to help new maintainers understand the code base....
it would have nice to just remove the unused codes and arrange the alignment and plus line spacing to as not to give chance to another issue related to #76 

either ways lets wait for @PreciousOritsedere review!!!

**Comment by PreciousOritsedere** [comment]
@ImaJin14 i did the light spacing alignment as well.
Also can you specify the code that’s meant for new contributors which I removed? because I came across some which seemed like commented instructions and I made sure to leave them there. I only took out commented css styles that have no purpose there.

**Comment by PreciousOritsedere** [comment]
@possumbilities Good day 😊 
I made a PR that fixes issues #65 and #76 . I’ll be awaiting your review please

**Comment by dikehprosper** [comment]
@PreciousOritsedere ma’am you took out some comments in your code base clean up

**Comment by PreciousOritsedere** [comment]
> @PreciousOritsedere ma’am you took out some comments in your code base clean up

Hi, can you please specify which ones? So I can be sure. You could attach screenshots if possible please

**Comment by dikehprosper** [comment]
Screenshot 2022-10-13 201704
Screenshot 2022-10-13 201758

**Comment by PreciousOritsedere** [comment]
> @PreciousOritsedere Screenshot 2022-10-13 201704
> Screenshot 2022-10-13 201758

Hey good morning, my thoughts was those comments might not be needed anymore.

@possumbilities are these comments relevant? If they are, I could update my commit and update this PR as well

**Comment by dikehprosper** [comment]
@PreciousOritsedere great job dear....you can know what to do next as soon as @possumbilities responds

**Comment by possumbilities** [comment]
@PreciousOritsedere I don't believe those specific comments are needed anymore. Internet Explorer 8 isn't officially supported by Microsoft anymore, and it's likely they were commented out to deprecate them at the time.

**Comment by PreciousOritsedere** [comment]
> @PreciousOritsedere I don't believe those specific comments are needed anymore. Internet Explorer 8 isn't officially supported by Microsoft anymore, and it's likely they were commented out to deprecate them at the time.

Okay great. Thank you :)

**Review by possumbilities — APPROVED** [review]
I tested it via Docker and all seems to work as expected. Approved. 

Thanks for consolidating all the formatting! ❤️

**Comment by PreciousOritsedere** [comment]
Yay! celebrating my first merge :) Thank you @possumbilities

**Comment by PreciousOritsedere** [comment]
Awesome 🤩

**Pull request merged**
