### PR TITLE
Removed default search button border

### LINKED ISSUE #304: [Bug] Search Button: Default Button Border Not Removed Across All Screen Sizes
## Description

The default border of the button was not removed for all screen sizes. The border is still visible on both desktop and mobile screens. It's essential to remove the default button border to maintain design consistency across the interface and avoid a cluttered or outdated appearance, especially when custom button styles are applied. And since the button has a background color, a border is not needed.

## Reproduction

1. Access the interface on a desktop or large screen device.
2. Observe that the button still has the default border.
3. Switch to a mobile device or use developer tools to simulate a mobile screen size.
4. Note that the button's default border is still visible.
5. See error.

## Expectation

The button’s default border should be removed consistently on all screen sizes to ensure a clean and modern appearance
## Screenshots

Desktop screen with default: 
defaultBorderPresent

Desktop screen without default border:
noDefaultBorder

Mobile screen with default border: 
mobileViewWithBorder

Mobile screen without default border:
mobileViewNoBorder

## Resolution

- [ ] I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by Macomi27**
## Fixes

- Fixes #304 by @SisiVero

## Description
This PR presents the issue of default button border present in the search button.
Here, the border has been removed for both desktop and mobile interfaces to maintain consistency.

## Screenshots

Screenshot 2024-10-20 021736
WhatsApp Image 2024-10-20 at 02 17 19

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source license" is equivalent to "open content license or public domain dedication."
<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by Macomi27** [comment]
> Hi @Macomi27 , well done. I just got to see your PR. It is not properly written, hence it not being linked to the issue. You can take a look at the one I created #308 and make changes to your description in other to properly link it to the issue. I will close mine once you update your description.

Thank you @SisiVero. Please can you check now to see that I'm on track?

**Comment by possumbilities** [comment]
Hi @Macomi27 this is looking very good! I think there's one more adjustment the edge of the button should be flush with the top and bottom border of the input area. So we don't' need to just remove the default border entirely, we need to overwrite it with a smaller black border so that the button and the input area (including its border) are the same height and flow seamlessly into one another.

**Comment by Macomi27** [comment]
Screenshot 2024-10-22 012319
@possumbilities kindly check the corrections I have made

**Review by possumbilities — APPROVED** [review]
@Macomi27 That's perfect. Thank you. Approved.

**Comment by possumbilities** [comment]
@Macomi27 If you respond to the original issue I can assign you!

**Pull request merged**
