### PR TITLE
refactors engine buttons

### LINKED ISSUE #159: [Feature] Refactor Search Engine buttons
## Problem

The current implementation of the search engine buttons needs refactoring in order to provide a more standard and stable implementation. 

This should also provide better fix for #155. Below is the current structure of the search engine buttons

```
<div class="engine">
       <div class="engineButton">
	  <button onclick="setEngine(this)" name="engine" value="ccmixter" id="ccmixter"></button>
       </div>
      <div class="engineDesc"><label for="ccmixter"><strong>ccMixter</strong><br/>Music</label></div>
</div>
```

## Description

Create minimal `<button>` elements for each search engine AND they should contain inner text: `<button>engineName</button>`.

Reference [this comment](https://github.com/creativecommons/search/issues/155#issuecomment-1297167324) as guide.

## Implementation

- [ ] I would be interested in implementing this feature.

### PR DESCRIPTION
**Pull request by JennySimen**
## Fixes

Fixes #159 by @JennySimen and #166 by @dikehprosper 

## Description

This PR changes the structure of the engine buttons in order to improve accessibility. The different HTML elements used to create the engine buttons are removed and only the `<button>` tag is used. The unused CSS classes are removed as well.

## Screenshots

Screen Shot 2022-11-11 at 17 51 47

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source license" is equivalent to "open content license or public domain dedication."
<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by possumbilities** [comment]
@JennySimen can you get the branch up to date and I'll review it further! Thanks! ❤️

**Comment by JennySimen** [comment]
@possumbilities right away

**Comment by JennySimen** [comment]
Hi @possumbilities, please I just updated the branch.

**Comment by possumbilities** [comment]
@JennySimen All seems sound, looks like that last PR merge made this out of date again, if you can do one last update we'll move forward with it after a final test on this end. ❤️

**Comment by JennySimen** [comment]
@possumbilities on it

**Comment by JennySimen** [comment]
@possumbilities I have updated the PR

**Comment by possumbilities** [comment]
@JennySimen Great work! 

Something I've noticed, it might be worthwhile to incorporate the work from #162 from @ImaJin14 so that they don't conflict with each other, and I can then give credit to both of you on this PR as combined work?

@ImaJin14 You OK with that?

**Comment by JennySimen** [comment]
@possumbilities I agree

**Comment by ImaJin14** [comment]
I agree @possumbilities 


@JennySimen please go ahead and implement the changes in #162

**Comment by JennySimen** [comment]
@possumbilities changes have been added on this branch

**Comment by possumbilities** [comment]
Closing with the acceptance of:
* #206

**Pull request closed without merging**
