### PR TITLE
cc_org.po.svn-base: fix typo in line 2339 (german)

### PR DESCRIPTION
**Pull request by xdevs23**
"beachten Sie, dass dies" instead of "beachten Sie, das dies"

### CODE REVIEW

**Comment by xdevs23** [comment]
Is anyone here?

**Comment by robmyers** [comment]
Hi!

We are here, I'm not sure how this got missed. Thank you very much for this correction!

**Comment by xdevs23** [comment]
No problem, thanks for merging my contributon.

**Comment by robmyers** [comment]
You're welcome. Thanks again!

**Pull request merged**
