### PR TITLE
Add focus visible to permissions checkbox

### LINKED ISSUE #126: [Feature] Add outline to checkbox input to improve accessibility
## Problem

There's an `outline: none;` set on all inputs when focused. This can cause accessibility issues for keyboard users. This feature will make the inputs, especially the checkbox input more accessible by styling its focused state so that there is a visible outline. 

In this screenshot, the checkbox is focused using the keyboard tab, there's a light blue focus around it which is barely visible.
Screenshot (49)

Compare to this screenshot that visibly shows that the checkbox is focused
Screenshot (50)

## Description

Usually, setting an `outline: none;` is not the best practice as it creates accessibility issues, especially for users who navigate the website using keyboards only. This feature will style the outline instead of setting it to none to be consistent with the website style. 

## Alternatives

Comments in the cc-wp/css/style.css file mention that the file should not be edited. An alternative will be to style the checkbox only instead, (which is the main visible issue on the website), which can be targeted using the id selector `#permissions input` in the creative-commons-search/style.css file.

## Implementation

- [x] I would be interested in implementing this feature.

### PR DESCRIPTION
**Pull request by mbonamensa**
## Fixes

Fixes #126  by @mbonamensa 

## Description

The new feature adds a `focus-visible` pseudo-class to the permissions checkbox input with a style that reverts `outline: none`  and creates a visible outline on tab-focus.

## Tests

1. Open CC search in the browser. 
2. Navigate through page using keyboard only (tabs)
3. See browser default outline on permissions checkbox.

## Screenshots

Screenshot (57)

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source license" is equivalent to "open content license or public domain dedication."
<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by possumbilities** [comment]
@mbonamensa Hi! Thank you for this, but it looks like the PR needs to be brought up to date, but as for functionality it seems sounds. 

Let me know when it's been brought current!

**Comment by mbonamensa** [comment]
@possumbilities done, please check. Thank you!

**Comment by mbonamensa** [comment]
Ahh, I'm a bit lost on how this works. I was trying to revert commits for the other issue I'm working on #167 
Will commits I make after making pull requests be added to the pull requests I made? A little confused here @possumbilities 
I hope the question makes sense😅

**Comment by ImaJin14** [comment]
> Ahh, I'm a bit lost on how this works. I was trying to revert commits for the other issue I'm working on #167 
> Will commits I make after making pull requests be added to the pull requests I made? A little confused here @possumbilities 
> I hope the question makes sense😅
> 

Yes it will... So as to change that effect you'll need to create a new branch and switch heads to it and push commits through it... Hope it's better understood??

**Comment by mbonamensa** [comment]
@ImaJin14 Ohh so I need a separate branch for the other commits?
But reverting them now will not add them here right?

**Comment by ImaJin14** [comment]
> @ImaJin14 Ohh so I need a separate branch for the other commits?
> But reverting them now will not add them here right?

Yes... Any commit that isn't in line with this PR you revert it create another branch and push the commits there

**Comment by mbonamensa** [comment]
> > @ImaJin14 Ohh so I need a separate branch for the other commits?
> > But reverting them now will not add them here right?
> 
> Yes... Any commit that isn't in line with this PR you revert it create another branch and push the commits there

Alright, thanks for your help!

**Review by possumbilities — APPROVED** [review]
Approved. Thank you!

**Comment by mbonamensa** [comment]
> Approved. Thank you!

Awesome 🤩

**Pull request merged**
