### PR TITLE
corrected a typing error in search.js file

### PR DESCRIPTION
**Pull request by FrancoFrancis**
Fixes:
*  #75
## Description
Fixed a typing Error in the Search.js file 

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source license" is equivalent to "open content license or public domain dedication."
<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by FrancoFrancis** [comment]
HI @TimidRobot  KINDLY REVIEW MY PR THANKS

**Comment by dikehprosper** [comment]
Great job 🙌@FrancoFrancis ….but I think you need to create an issue for this PR first….
According to this guideline 
https://opensource.creativecommons.org/contributing-code/

**Comment by dikehprosper** [comment]
> Great job 🙌@FrancoFrancis ….but sir I think you need to create an issue for this PR first….
> According to this guideline
> https://opensource.creativecommons.org/contributing-code/

**Review by ImaJin14 — APPROVED** [review]

**Comment by possumbilities** [comment]
@FrancoFrancis excellent find! Can you also make the relevant Issue and then reference it here?

**Comment by ImaJin14** [comment]
@FrancoFrancis you can link this PR to the issue #75 which elaborates on what your PR does

**Comment by FrancoFrancis** [comment]
Thank you so much guys 

> @FrancoFrancis you can link this PR to the issue #75 which elaborates on what your PR does

thank you so much👍🏾

**Comment by ImaJin14** [comment]
> Thank you so much guys 
> 
> > @FrancoFrancis you can link this PR to the issue #75 which elaborates on what your PR does
> 
> thank you so much👍🏾 

You still need to reference this PR to the issue 


Your welcome....

**Comment by FrancoFrancis** [comment]
> @FrancoFrancis excellent find! Can you also make the relevant Issue and then reference it here?

ok thanks on it 😎

**Review by possumbilities — APPROVED** [review]
Thank you for this! ❤️ Approved.

**Comment by FrancoFrancis** [comment]
> Thank you for this! ❤️ Approved.

thank you to you too @possumbilities

**Comment by FrancoFrancis** [comment]
> deployed to production `Fri Oct 14 05:32:20 BST 2022`. it may take ~30 minutes for caches to clear

thanks @TimidRobot

**Pull request merged**
