### PR TITLE
Update Readme.md

### PR DESCRIPTION
**Pull request by PreciousOritsedere**
## Fixes

Fixes #68   by @PreciousOritsedere

## Description
Added more distinctive instructions to the readme.md

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source license" is equivalent to "open content license or public domain dedication."
<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by ImaJin14** [comment]
@PreciousOritsedere I think it's best you close pr #68 to avoid duplicates

**Comment by PreciousOritsedere** [comment]
I think @possumbilities or @TimidRobot  is in the best position to review both and determine which one to close.

**Comment by ImaJin14** [comment]
This PR is already out of the scope of the linked issue

**Comment by PreciousOritsedere** [comment]
@ImaJin14 how please? Can you explain further

**Comment by ImaJin14** [comment]
Your issue states improvement on readme.md file but your commits show that you've changed more than just the readme.md file


I suggest you revert changes and resolve just the readme.md adjustments

**Comment by PreciousOritsedere** [comment]
I was actually attempting to create another PR. But I think the commit merged into this. Because I couldn’t see the option to create a different Pr. I think the first one has to be merged first before I can create again

**Comment by possumbilities** [comment]
@PreciousOritsedere I'm going to close this PR since it's got extra changes not relevant to the Issue, and suggest you wait to try again until the original Issue #68 is fully approved.

**Pull request closed without merging**
