### PR TITLE
criteria_for_inclusion_of_external_sources (Search Engines)

### LINKED ISSUE #112: [Feature] Create a guide on criteria for how search engines are selected and prioritized for inclusion
## Problem
There is currently no guide that states the criteria  to identify search engines that can be integrated into the the project 

## Description
The guide will contain detailed criteria on the how search engines to are selected for inclusion in the project 

## Implementation

-  [x]  I would be interested in implementing this feature.

### PR DESCRIPTION
**Pull request by Marshalng**
A guide on selection of external sources 

## Fixes

Fixes #112  by @Marshalng

## Description
As contributors seek to integrate more search engines as External Sources on  Creative Commons Search to enhance its effectiveness, this guide will help them identify important factors to bear in mind when considering these search engines in line with the goals of Creative Commons Search.

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source license" is equivalent to "open content license or public domain dedication."
<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by possumbilities** [comment]
Hi @Marshalng thank you for contributing! 

The guide name does not follow the standards outlined here: https://github.com/creativecommons/search/tree/main/guides

* the file name should be in [snake_case](https://en.wikipedia.org/wiki/Snake_case). You instead appended ` (Search Engines)` at the end, this is not a valid `snake_case` name
* the file should be in `markdown` format, and as such should have the `.md` extension, currently it has no extension
* I might also suggest a change in name to something like: `search_engines_inclusion_criteria.md` since that is a little more clear when scanning the names as the list of guides grows. I'm open to iterations/versions of this, but I think the current `criteria_for_inclusion_of_external_sources` is not quite clear enough.

**Comment by Marshalng** [comment]
Thank you for your guidance @possumbilities  , I will effect the changes immediately.

**Comment by Marshalng** [comment]
Changes effected @possumbilities , please check. Thanks

**Review by possumbilities — APPROVED** [review]
Thank you for this, this should allow us to keep building upon it as time goes and serve as a good place to point people from now one. ❤️

**Pull request merged**
