### PR TITLE
Dividing Styles into Two Distinct Sections #276

### PR DESCRIPTION
**Pull request by mannika763**
## Fixes

- Fixes creativecommons/search#289 by @SisiVero 

## Description
I've separated the style.css code according to the rules.
The style rules are now divided into two sections, separated by an empty line. Additionally, I’ve added some comments to make it clearer for others in the future.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source license" is equivalent to "open content license or public domain dedication."
<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by Queen-codes** [comment]
hi @mannika763 . This pull request links to an issue that has not been marked ready for work. I think you mistakenly linked it to this one. There's a duplicate of this issue at #277 that has the appropriate label.

**Comment by mannika763** [comment]
Hi @Queen-codes 
In #276, it mentions making changes in the style.js file, and in #277, changes are required in the vocabulary.css file. However, this PR involves changes to the style.css file. I wasn't aware that an issue needs the 'ready for work' tag before we can start working on it.

**Comment by Queen-codes** [comment]
> Hi @Queen-codes In #276, it mentions making changes in the style.js file, and in #277, changes are required in the vocabulary.css file. However, this PR involves changes to the style.css file. I wasn't aware that an issue needs the 'ready for work' tag before we can start working on it.

oh, yeah. it does. i hope this helps you moving forward

**Comment by possumbilities** [comment]
The separate sections don't need commented headers, just the one line separation of space.

**Comment by possumbilities** [comment]
Fixed by:
- #294
 
Closing.

**Pull request closed without merging**
