### PR TITLE
improve readability by fixing tab inconsistencies

### LINKED ISSUE #84: [Bug] <Improve readability by correcting tab inconsistencies in home-buckets.php>
## Description
 The tab inconsistencies and spacing make the code difficult to read even with the comments indicating closing tags.

## Reproduction

1. Open cc search in the editor
2. Navigate to cc-wp/home-buckets.php 
3. Check lines 3-5, 74-108 
4. See error.

## Expectation
I expected to see indexing in the code that would make it a bit more readable 

## Screenshots
Screenshot (38)

## Resolution
- [x] I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by mbonamensa**
## Fixes

Fixes #84  by @mbonamensa

## Description

The tab inconsistencies in the home-buckets.php make the code difficult to read. This fix removes unnecessary tabs and creates a uniform indentation. This makes the code look clean and readable.

## Screenshots

Problem
Screenshot (38)

Solution
Screenshot (41)

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source license" is equivalent to "open content license or public domain dedication."
<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by mbonamensa** [comment]
@possumbilities @TimidRobot  I didn't check the second checkbox because I am not sure what that means. Does it mean I have to merge with my main branch first? Anyone else who knows and can help? Thanks.

**Comment by dikehprosper** [comment]
@mbonamensa you can tick that, it simply means you are requesting a PR that targets the main branch i.e an update to the files cloned by all interns

**Comment by mbonamensa** [comment]
> @mbonamensa you can tick that, it simply means you are requesting a PR that targets the main branch i.e an update to the files cloned by all interns

Oh okay. Thanks.

**Comment by possumbilities** [comment]
Thank you so very much for your contribution, but I'm closing this PR. Please see this comment for further details: https://github.com/creativecommons/search/issues/84#issuecomment-1279422799

**Pull request closed without merging**
